load("//tools/base/bazel:bazel.bzl", "iml_module")
load("//tools/base/bazel:expand_template.bzl", "expand_template")
load("//tools/base/bazel:gradle.bzl", "gradle_build")
load("//tools/base/bazel:jvm_import.bzl", "jvm_import")
load("//tools/base/bazel:kotlin.bzl", "kotlin_test")
load("//tools/base/bazel:maven.bzl", "maven_library", "maven_repository")
load("//tools/base/bazel:utils.bzl", "fileset", "java_jarjar", "merged_zip")
load("//tools/base/common:version.bzl", "BUILD_VERSION", "DEV_BUILD_VERSION", "RELEASE_BUILD_VERSION")

exports_files(["databinding.properties"])

# managed by go/iml_to_build
iml_module(
    name = "studio.baseLibrary",
    srcs = ["baseLibrary/src/main/java"],
    iml_files = ["baseLibrary/db-baseLibrary.iml"],
    jvm_target = "8",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "@intellij//:intellij-sdk",
        "@intellij//:com.intellij.java",
        "//prebuilts/tools/common/m2:junit-4.12[test]",
        "//prebuilts/tools/common/m2:hamcrest-core-1.3[test]",
    ],
)

# managed by go/iml_to_build
iml_module(
    name = "studio.baseLibrarySupport",
    srcs = ["baseLibrarySupport/src/main/java"],
    iml_files = ["baseLibrarySupport/db-baseLibrarySupport.iml"],
    jvm_target = "8",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "@intellij//:intellij-sdk",
        "@intellij//:com.intellij.java",
        "//prebuilts/tools/common/m2:junit-4.12[test]",
        "//prebuilts/tools/common/m2:hamcrest-core-1.3[test]",
    ],
)

maven_library(
    name = "tools.baseLibrary",
    srcs = glob(["baseLibrary/src/main/java/**"]),
    coordinates = "androidx.databinding:databinding-common",
    description = "Shared library between Data Binding runtime lib and compiler",
    javacopts = ["--release 8"],
    notice = "baseLibrary/NOTICE",
    resource_strip_prefix = "tools/data-binding/baseLibrary",
    version = BUILD_VERSION,
    visibility = ["//visibility:public"],
)

maven_library(
    name = "tools.baseLibrarySupport",
    srcs = glob(["baseLibrarySupport/src/main/java/**"]),
    coordinates = "com.android.databinding:baseLibrary",
    description = "Shared library between Data Binding runtime lib and compiler",
    javacopts = ["--release 8"],
    notice = "baseLibrary/NOTICE",
    resource_strip_prefix = "tools/data-binding/baseLibrary",
    version = BUILD_VERSION,
    visibility = ["//visibility:public"],
)

java_jarjar(
    name = "compilerCommon.antlr_runtime.shaded_jar",
    srcs = [
        "//prebuilts/tools/common/m2:antlr4-runtime",
    ],
    rules = "jarjar_rules.txt",
)

# managed by go/iml_to_build
jvm_import(
    name = "compilerCommon.antlr_runtime.shaded",
    jars = ["//tools/data-binding:compilerCommon.antlr_runtime.shaded_jar.jar"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "compilerCommon.antlr",
    # buildifier: disable=bad-recursive-glob
    srcs = glob([
        "compilerCommon/src/main/xml-gen/**/*.java",
        "compilerCommon/src/main/grammar-gen/**/*.java",
    ]),
    deps = [
        "//prebuilts/tools/common/m2:antlr4-runtime",
    ],
)

java_jarjar(
    name = "compilerCommon.antlr.shaded_jar",
    srcs = [
        ":compilerCommon.antlr",
    ],
    rules = "jarjar_rules.txt",
)

# managed by go/iml_to_build
jvm_import(
    name = "compilerCommon.antlr.shaded",
    jars = ["//tools/data-binding:compilerCommon.antlr.shaded_jar.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
iml_module(
    name = "studio.compilerCommon",
    # do not sort: must match IML order
    srcs = [
        "compilerCommon/src/main/java",
        "compilerCommon/src/main/kotlin",
    ],
    iml_files = ["compilerCommon/db-compilerCommon.iml"],
    jvm_target = "8",
    lint_baseline = "lint_baseline.xml",
    test_srcs = [
        "compilerCommon/src/test/java",
        "compilerCommon/src/test/kotlin",
    ],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/data-binding:studio.baseLibrary",
        "//tools/data-binding:studio.baseLibrarySupport",
    ],
    # do not sort: must match IML order
    deps = [
        "//tools/data-binding:compilerCommon.antlr_runtime.shaded",
        "//tools/data-binding:compilerCommon.antlr.shaded",
        "@intellij//:intellij-sdk",
        "@intellij//:com.intellij.java",
        "//tools/data-binding:studio.baseLibrary[module]",
        "//tools/data-binding:studio.baseLibrarySupport[module]",
        "//tools/base/annotations:studio.android.sdktools.android-annotations[module]",
        "//prebuilts/tools/common/m2:juniversalchardet",
        "//prebuilts/tools/common/m2:javapoet",
        "//prebuilts/tools/common/m2:jetifier-core",
        "//tools/adt/idea/.idea/libraries:compile-testing[test]",
        "//tools/adt/idea/.idea/libraries:truth[test]",
    ],
)

LATEST_STABLE_DATA_BINDING_BUILD_VERSION = "8.5.0"

expand_template(
    name = "data_binding_version_info",
    out = "data_binding_version_info.properties",
    substitutions = select({
        "//tools/base/bazel:without_vendor": {
            "{BUILD_VERSION}": LATEST_STABLE_DATA_BINDING_BUILD_VERSION,
        },
        "//tools/base/bazel:release": {
            "{BUILD_VERSION}": RELEASE_BUILD_VERSION,
        },
        "//conditions:default": {
            "{BUILD_VERSION}": DEV_BUILD_VERSION,
        },
    }),
    template = "runtime_version.properties.template",
    visibility = ["//visibility:public"],
)

fileset(
    name = "tools.compilerCommon.resources",
    srcs = [
        ":data_binding_version_info",
    ],
    mappings = {
        "compilerCommon/": "",
    },
)

maven_library(
    name = "tools.compilerCommon",
    # buildifier: disable=bad-recursive-glob
    srcs = glob([
        "compilerCommon/src/main/java/**/*.java",
        "compilerCommon/src/main/java/**/*.kt",
        "compilerCommon/src/main/kotlin/**/*.java",
        "compilerCommon/src/main/kotlin/**/*.kt",
    ]),
    bundled_deps = [
        ":compilerCommon.antlr_runtime.shaded",
        ":compilerCommon.antlr.shaded",
    ],
    coordinates = "androidx.databinding:databinding-compiler-common",
    description = "Common library that can be shared between different build tools",
    module_name = "databinding-compiler-common",
    notice = "compilerCommon/NOTICE",
    resource_strip_prefix = "tools/data-binding",
    resources = [":tools.compilerCommon.resources"],
    version = BUILD_VERSION,
    visibility = ["//visibility:public"],
    deps = [
        ":tools.baseLibrary",
        ":tools.baseLibrarySupport",
        "//tools/base/annotations",
        "@maven//:com.android.tools.build.jetifier.jetifier-core",
        "@maven//:com.google.code.gson.gson",
        "@maven//:com.google.guava.guava",
        "@maven//:com.googlecode.juniversalchardet.juniversalchardet",
        "@maven//:com.squareup.javapoet",
        "@maven//:commons-io.commons-io",
        "@maven//:org.glassfish.jaxb.jaxb-runtime",
        "@maven//:org.jetbrains.kotlin.kotlin-stdlib-jdk8",
    ],
)

kotlin_test(
    name = "tools.compilerCommon_tests",
    # buildifier: disable=bad-recursive-glob
    srcs = glob([
        "compilerCommon/src/test/**/*.kt",
        "compilerCommon/src/test/**/*.java",
    ]),
    jvm_flags = ["-Dtest.suite.jar=tests.jar"],
    test_class = "com.android.testutils.JarTestSuite",
    runtime_deps = ["//tools/base/testutils:tools.testutils"],
    deps = [
        ":tools.compilerCommon",
        "//tools/base/bazel:langtools",
        "@maven//:com.google.testing.compile.compile-testing",
        "@maven//:com.google.truth.truth",
        "@maven//:junit.junit",
    ],
)

# managed by go/iml_to_build
iml_module(
    name = "studio.compiler",
    # do not sort: must match IML order
    srcs = [
        "compiler/src/main/java",
        "compiler/src/main/kotlin",
    ],
    iml_files = ["compiler/db-compiler.iml"],
    jvm_target = "8",
    lint_baseline = "studio_compiler_lint_baseline.xml",
    resources = ["compiler/src/main/resources"],
    test_data = [
        "//prebuilts/studio/sdk:platform-tools",
        "//prebuilts/studio/sdk:platforms/latest",
    ],
    test_srcs = ["compiler/src/test/java"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/data-binding:studio.baseLibrary",
        "//tools/data-binding:studio.baseLibrarySupport",
    ],
    # do not sort: must match IML order
    deps = [
        "//tools/data-binding:compilerCommon.antlr_runtime.shaded",
        "//tools/data-binding:compilerCommon.antlr.shaded",
        "@intellij//:intellij-sdk",
        "@intellij//:com.intellij.java",
        "//tools/adt/idea/.idea/libraries:kotlin-test[test]",
        "//tools/data-binding:studio.baseLibrary[module]",
        "//tools/data-binding:studio.baseLibrarySupport[module]",
        "//tools/base/annotations:studio.android.sdktools.android-annotations[module]",
        "//tools/data-binding:studio.compilerCommon[module]",
        "//prebuilts/tools/common/m2:juniversalchardet",
        "//prebuilts/tools/common/m2:commons-lang",
        "//tools/adt/idea/.idea/libraries:mockito[test]",
        "//prebuilts/tools/common/m2:javapoet",
        "//prebuilts/tools/common/m2:auto-common",
        "//tools/adt/idea/.idea/libraries:compile-testing[test]",
        "//tools/adt/idea/.idea/libraries:truth[test]",
    ],
)

# TODO: Use the right version of kotlin-compiler.
maven_library(
    name = "tools.compiler",
    # buildifier: disable=bad-recursive-glob
    srcs = glob([
        "compiler/src/main/java/**/*.java",
        "compiler/src/main/java/**/*.kt",
        "compiler/src/main/kotlin/**/*.kt",
    ]),
    coordinates = "androidx.databinding:databinding-compiler",
    description = "The annotation processor for Data Binding. Generates binding classes for runtime.",
    module_name = "databinding-compiler",
    notice = "compiler/src/main/resources/NOTICE.txt",
    resource_strip_prefix = "tools/data-binding/compiler/src/main/resources",
    resources = glob(
        include = ["compiler/src/main/resources/**"],
        exclude = ["compiler/src/main/resources/NOTICE.txt"],
    ),
    version = BUILD_VERSION,
    visibility = ["//visibility:public"],
    deps = [
        ":tools.baseLibrary",
        ":tools.compilerCommon",
        "//tools/base/annotations",
        "@maven//:com.google.auto.auto-common",
        "@maven//:com.google.code.gson.gson",
        "@maven//:com.google.guava.guava",
        "@maven//:com.googlecode.juniversalchardet.juniversalchardet",
        "@maven//:com.squareup.javapoet",
        "@maven//:commons-codec.commons-codec",
        "@maven//:commons-io.commons-io",
        "@maven//:org.glassfish.jaxb.jaxb-runtime",
        "@maven//:org.jetbrains.kotlin.kotlin-stdlib-jdk8",
    ],
)

kotlin_test(
    name = "tools.compiler_tests",
    # buildifier: disable=bad-recursive-glob
    srcs = glob([
        "compiler/src/test/**/*.kt",
        "compiler/src/test/**/*.java",
    ]),
    data = [
        "//prebuilts/studio/sdk:platform-tools",
        "//prebuilts/studio/sdk:platforms/latest",
    ],
    jvm_flags = ["-Dtest.suite.jar=tests.jar"],
    test_class = "com.android.testutils.JarTestSuite",
    runtime_deps = ["//tools/base/testutils:tools.testutils"],
    deps = [
        ":tools.baseLibrary",
        ":tools.compiler",
        ":tools.compilerCommon",
        "//tools/base/bazel:langtools",
        "@maven//:com.google.testing.compile.compile-testing",
        "@maven//:com.google.truth.truth",
        "@maven//:commons-io.commons-io",
        "@maven//:junit.junit",
        "@maven//:org.jetbrains.kotlin.kotlin-test",
        "@maven//:org.mockito.mockito-core",
    ],
)

maven_repository(
    name = "external_deps",
    # keep sorted
    artifacts = [
        "@maven//:android.arch.lifecycle.compiler_1.0.0",
        "@maven//:android.arch.lifecycle.extensions_1.0.0",
        "@maven//:androidx.appcompat.appcompat_1.0.2",
        "@maven//:androidx.lifecycle.lifecycle-extensions_2.2.0",
        "@maven//:androidx.lifecycle.lifecycle-livedata-ktx_2.6.1",
        "@maven//:androidx.lifecycle.lifecycle-process_2.6.1",
        "@maven//:androidx.lifecycle.lifecycle-runtime-ktx_2.6.1",
        "@maven//:androidx.lifecycle.lifecycle-runtime_2.6.1",
        "@maven//:androidx.lifecycle.lifecycle-service_2.6.1",
        "@maven//:androidx.lifecycle.lifecycle-viewmodel-ktx_2.6.1",
        "@maven//:androidx.test.espresso.espresso-core_3.5.1",
        "@maven//:com.android.support.appcompat-v7_26.1.0",
        "@maven//:com.android.support.cardview-v7_26.1.0",
        "@maven//:com.github.gundy.semver4j_0.16.4",
        "@maven//:com.google.android.material.material_1.0.0",
        "@maven//:com.google.code.findbugs.jsr305_1.3.9",
        "@maven//:com.google.errorprone.error_prone_annotations_2.1.3",
        "@maven//:de.undercouch.gradle-download-task_4.0.2",
        "@maven//:org.jetbrains.intellij.deps.trove4j_1.0.20181211",
        "@maven//:org.jetbrains.kotlin.kotlin-bom_1.8.0",
        "@maven//:org.jetbrains.kotlinx.kotlinx-coroutines-android_1.4.1",
        "@maven//:org.junit.junit-bom_5.9.3",
    ],
)

GRADLE_PROPERTIES = select({
    "//tools/base/bazel:release": {
        "version": RELEASE_BUILD_VERSION,
    },
    "//conditions:default": {
        "version": DEV_BUILD_VERSION,
    },
})

gradle_build(
    name = "runtimeLibrariesAndroidX",
    build_file = "extensions/build.gradle",
    data = [
        "//prebuilts/studio/sdk:build-tools/latest",
        "//prebuilts/studio/sdk:platform-tools",
        "//prebuilts/studio/sdk:platforms/latest",
        "//tools/base/build-system:gradle-distrib",
        "//tools/base/common:agp_gradle_build_files",
        "//tools/buildSrc/base:dependencies.properties",
        "//tools/data-binding:databinding.properties",
    ] + glob(
        ["extensions/**"],
        exclude = [
            "extensions/.gradle/**",
            "extensions/build/**",
            "extensions/local.properties",
            "extensions/**/build",
            "extensions/gradle/**",
            "extensions/gradlew",
            "extensions/gradlew.bat",
        ],
    ),
    gradle_properties = GRADLE_PROPERTIES,
    max_workers = 1,  # b/155772061
    output_file = "data_binding_runtime_androidx.zip",
    output_file_source = "local_repo_zip/dataBindingRuntimeRepo.zip",
    repo_zips = [
        "//tools/base/build-system:android_gradle_plugin.zip",
    ],
    repos = [
        ":external_deps",
        "//tools/base/build-system:android_gradle_plugin_runtime_dependencies",
        "//tools/base/third_party/kotlin:kotlin-m2repository",
    ],
    tasks = ["createArchive"],
)

gradle_build(
    name = "runtimeLibrariesSupport",
    build_file = "extensions-support/build.gradle",  #TODO rename to extensionSupport
    data = [
        "//prebuilts/studio/sdk:build-tools/latest",
        "//prebuilts/studio/sdk:platform-tools",
        "//prebuilts/studio/sdk:platforms/latest",
        "//tools/base/build-system:gradle-distrib",
        "//tools/base/common:agp_gradle_build_files",
        "//tools/data-binding:databinding.properties",
    ] + glob(
        ["extensions-support/**"],
        exclude = [
            "extensions-support/.gradle/**",
            "extensions-support/build/**",
            "extensions-support/local.properties",
            "extensions-support/**/build",
            "extensions-support/gradle/**",
            "extensions-support/gradlew",
            "extensions-support/gradlew.bat",
        ],
    ),
    gradle_properties = GRADLE_PROPERTIES,
    max_workers = 1,  # b/155772061
    output_file = "data_binding_runtime_support.zip",
    output_file_source = "local_repo_zip/dataBindingRuntimeRepo.zip",
    repo_zips = [
        "//tools/base/build-system:android_gradle_plugin.zip",
    ],
    repos = [
        ":external_deps",
        "//tools/base/build-system:android_gradle_plugin_runtime_dependencies",
        "//tools/base/third_party/kotlin:kotlin-m2repository",
    ],
    tasks = ["createArchive"],
)

filegroup(
    name = "integration-test-projects",
    srcs = glob(
        ["integration-tests/**"],
        exclude = [
            "**/build/**",
            "**/.gradle/**",
        ],
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "integration-test-projects-support",
    srcs = glob(
        ["integration-tests-support/**"],
        exclude = [
            "**/build/**",
            "**/.gradle/**",
        ],
    ),
    visibility = ["//visibility:public"],
)

merged_zip(
    name = "data_binding_runtime",
    srcs = [
        "//tools/data-binding:data_binding_runtime_androidx.zip",
        "//tools/data-binding:data_binding_runtime_support.zip",
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "runtimeLibraries",
    actual = ":data_binding_runtime",
    visibility = ["//visibility:public"],
)
