buildToolsVersion = 30.0.2
compileSdkVersionStr=android-31
compileSdkVersionInt=31
# java versions for the code that runs on the device
javaTargetCompatibility = 1.8
javaSourceCompatibility = 1.8
# java versions for the code that runs on the host machine
compilerJavaTargetCompatibility = 1.8
compilerJavaSourceCompatibility = 1.8
group=androidx.databinding
testGroup=androidx.databinding.test
licenseName=The Apache Software License, Version 2.0
licenseUrl=http://www.apache.org/licenses/LICENSE-2.0.txt
licenseDistribution=repo
